#!/bin/sh
if [ -n "$PUSH_REMOTE" ]; then
	if [ "$VCS" = git ] && [ -d .git ]; then
		for REMOTE in $PUSH_REMOTE; do
			if [ -z "$PUSH_REMOTE_BRANCH" ]; then
				PUSH_REMOTE_BRANCH='master'
			fi
			git push "$REMOTE" "$PUSH_REMOTE_BRANCH" || true
		done
	elif [ "$VCS" = hg ] && [ -d .hg ]; then
		for REMOTE in $PUSH_REMOTE; do
			hg push "$REMOTE" || true
		done
	else
		echo "PUSH_REMOTE not yet supported for $VCS" >&2
	fi
fi
